package com.mycompany.imageumbral;

import java.awt.Dimension;
import java.awt.Point;
import java.io.File;
import static java.util.Locale.filter;
import javax.swing.JDesktopPane;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class IntFrameUmbralizada extends javax.swing.JInternalFrame {
    
    private JFileChooser fc = new JFileChooser();
    private JOptionPane dialog = new JOptionPane();
    private JDesktopPane ventanaPr;

    public IntFrameUmbralizada(String umbral, File imgUmb, JDesktopPane ventPr) {
        initComponents();
        this.setPreferredSize(new Dimension(1000,1000));
        this.setMaximizable(true);
        this.setIconifiable(true);
        this.setClosable(true);
        this.setResizable(false);
        ventanaPr = ventPr;
        titleUmbral.setText("Umbral = " + umbral);
        lienzo.updateImage(imgUmb);
        lienzo.umbralizar(Integer.parseInt(umbral));  
        adjustPosition();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleUmbral = new javax.swing.JLabel();
        lienzo = new com.mycompany.imageumbral.Lienzo();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        guardarMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        inforMenuItem = new javax.swing.JMenuItem();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
        });

        titleUmbral.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleUmbral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lienzo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        fileMenu.setText("File");

        guardarMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        guardarMenuItem.setText("Save");
        guardarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(guardarMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText("Help");

        inforMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        inforMenuItem.setText("About");
        inforMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inforMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(inforMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(titleUmbral, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(titleUmbral, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarMenuItemActionPerformed
        if(lienzo.isImage()){
            if(fc.showSaveDialog(null) == JFileChooser.APPROVE_OPTION){
                lienzo.saveImage(fc.getSelectedFile());
            }
        }else{
            dialog.showMessageDialog(null,"No se está visualizando ninguna imagen actualmente en la aplicación","Imagen no encontrada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_guardarMenuItemActionPerformed

    private void inforMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inforMenuItemActionPerformed
        dialog.showMessageDialog(null,"Mediante esta aplicación:\n1. Usted puede seleccionar una imagen '.jpg' o '.png' en el menu File en la opción Open o con el botón 'Open Image'.\n2. Una vez escogida la imagen, se muestra por una ventana interna.\n3. Para umbralizar la imagen, seleccione el menu Filter de la ventana interna de la imagen original y su opción Threshold.\n4. Para guardar la imagen umbralizada, seleccionamos el menu File la opción Save en la ventana interna umbralizada. ","Acerca de", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_inforMenuItemActionPerformed

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        adjustPosition();
    }//GEN-LAST:event_formComponentMoved

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem guardarMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem inforMenuItem;
    private com.mycompany.imageumbral.Lienzo lienzo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel titleUmbral;
    // End of variables declaration//GEN-END:variables

    private void adjustPosition() {
        double anchoPr = ventanaPr.getWidth();
        double alturaPr = ventanaPr.getHeight();
        Point PointVen = this.getLocation();
        double anchoV = this.getWidth();
        double alturaV = this.getHeight();
        Point newPosition = new Point((int)PointVen.getX(), (int)PointVen.getY());
        if(PointVen.getY() < 0){
            newPosition.setLocation(newPosition.getX(),0);
        }else{
            if(PointVen.getY()+alturaV > alturaPr){
                newPosition.setLocation(PointVen.getX(),(alturaPr - alturaV));
            }
        }
        if(PointVen.getX() < 0){
            newPosition.setLocation(0, newPosition.getY());
        }else{
            if(PointVen.getX()+anchoV > anchoPr){
                newPosition.setLocation((anchoPr - anchoV), PointVen.getY());
            }   
        }
        this.setLocation(newPosition);
    }
}
